### PR TITLE
Bacon test fest

### PR DESCRIPTION
**Pull request by stefanotorresi**
do u haz teh tests?

### CODE REVIEW

**Comment by snapshotpl** [comment]
@DASPRiD are you planning to develop this module? I think is great but it needs some improvements.

**Comment by DASPRiD** [comment]
@snapshotpl do you have anything specific in mind?

**Comment by stefanotorresi** [comment]
@DASPRiD aww u still didn't merge this? lazy man! :p

**Comment by snapshotpl** [comment]
Easier download/update unidecoder tables, remove dependencies and statics. This pr is hangs half year and @stefanotorresi is disappointed ;-)

**Comment by DASPRiD** [comment]
@stefanotorresi I'll merge it this weekend ;)
@snapshotpl The unidecoder tables don't change usually, at least they are still the same since I created this module ;)

**Comment by snapshotpl** [comment]
In repo you have 0.04.12, on Unidecode page is 0.04.14. I'm think also unidecoder tables shouldn't be merged in this module.

**Comment by DASPRiD** [comment]
@snapshotpl I have to convert them to a format I can read, so yes, they should be in here, making a separate module for them would be pointless.

**Comment by DASPRiD** [comment]
@snapshotpl Anyway, feel free to update the tables ;)

**Comment by snapshotpl** [comment]
OK, I will update some code after you merge this test, deal? :-)

**Comment by DASPRiD** [comment]
@snapshotpl Guess that sounds like a deal ;)

**Pull request merged**
